apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Values.cowboyAppName }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.cowboyAppName }}
  ports:
    - protocol: TCP
      port: 50051
      targetPort: grpc
