apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.cowboyAppName }}
  labels:
    app: {{ .Values.cowboyAppName }}
spec:
  serviceName: {{ .Values.cowboyAppName }}
  podManagementPolicy: Parallel
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.cowboyAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.cowboyAppName }}
    spec:
      containers:
        - name: {{ .Values.cowboyAppName }}
          image: {{ .Values.cowboyImage }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.grpcPort }}
              name: grpc
            - containerPort: {{ .Values.readinessPort }}
              name: ready
          resources:
            requests:
              cpu: 10m
              memory: 8Mi
            limits:
              cpu: 20m
              memory: 16Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: ready
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: {{ .Chart.Name }}
              mountPath: /{{ .Chart.Name }}
      volumes:
        - name: {{ .Chart.Name }}
          configMap:
            name: {{ .Chart.Name }}
