apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cowboyAppName }}
  labels:
    app: {{ .Values.cowboyAppName }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.cowboyAppName }}
  ports:
    - protocol: TCP
      port: {{ .Values.grpcPort }}
      targetPort: grpc
