apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cowboyControllerAppName }}
  labels:
    app: {{ .Values.cowboyControllerAppName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cowboyControllerAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.cowboyControllerAppName }}
    spec:
      containers:
        - name: {{ .Values.cowboyControllerAppName }}
          image: {{ .Values.cowboyControllerImage }}
          imagePullPolicy: IfNotPresent
          env:
            - name: REPLICAS
              value: "{{ .Values.replicas }}"
          ports:
            - containerPort: {{ .Values.readinessPort }}
              name: ready
          readinessProbe:
            httpGet:
              path: /ready
              port: ready
            initialDelaySeconds: 5
            periodSeconds: 5
