apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.etcdAppName }}
spec:
  serviceName: {{ .Values.etcdAppName }}
  selector:
    matchLabels:
      app: {{ .Values.etcdAppName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.etcdAppName }}
    spec:
      containers:
        - name: {{ .Values.etcdAppName }}
          image: quay.io/coreos/etcd:v3.5.1
          command:
            - etcd
          args:
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://etcd:2379
          ports:
            - containerPort: {{ .Values.etcdPort }}
              name: client
