apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.etcdAppName }}
spec:
  selector:
    app: {{ .Values.etcdAppName }}
  ports:
    - name: client
      protocol: TCP
      port: {{ .Values.etcdPort }}
      targetPort: {{ .Values.etcdPort }}
  type: ClusterIP
