// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.12
// source: api/proto/damage/damage.proto

package damagepb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DamageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From   int64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Damage int64 `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`
}

func (x *DamageRequest) Reset() {
	*x = DamageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_damage_damage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DamageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DamageRequest) ProtoMessage() {}

func (x *DamageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_damage_damage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DamageRequest.ProtoReflect.Descriptor instead.
func (*DamageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_damage_damage_proto_rawDescGZIP(), []int{0}
}

func (x *DamageRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *DamageRequest) GetDamage() int64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

var File_api_proto_damage_damage_proto protoreflect.FileDescriptor

var file_api_proto_damage_damage_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x6d, 0x61,
	0x67, 0x65, 0x2f, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x70, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x0d, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x61, 0x6d,
	0x61, 0x67, 0x65, 0x32, 0x51, 0x0a, 0x0d, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x44,
	0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x70, 0x62,
	0x2e, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x24, 0x5a, 0x22, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x65,
	0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x6d,
	0x61, 0x67, 0x65, 0x3b, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_damage_damage_proto_rawDescOnce sync.Once
	file_api_proto_damage_damage_proto_rawDescData = file_api_proto_damage_damage_proto_rawDesc
)

func file_api_proto_damage_damage_proto_rawDescGZIP() []byte {
	file_api_proto_damage_damage_proto_rawDescOnce.Do(func() {
		file_api_proto_damage_damage_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_damage_damage_proto_rawDescData)
	})
	return file_api_proto_damage_damage_proto_rawDescData
}

var file_api_proto_damage_damage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_damage_damage_proto_goTypes = []interface{}{
	(*DamageRequest)(nil), // 0: damagepb.DamageRequest
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_api_proto_damage_damage_proto_depIdxs = []int32{
	0, // 0: damagepb.DamageService.ReceiveDamage:input_type -> damagepb.DamageRequest
	1, // 1: damagepb.DamageService.ReceiveDamage:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_damage_damage_proto_init() }
func file_api_proto_damage_damage_proto_init() {
	if File_api_proto_damage_damage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_damage_damage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DamageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_damage_damage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_damage_damage_proto_goTypes,
		DependencyIndexes: file_api_proto_damage_damage_proto_depIdxs,
		MessageInfos:      file_api_proto_damage_damage_proto_msgTypes,
	}.Build()
	File_api_proto_damage_damage_proto = out.File
	file_api_proto_damage_damage_proto_rawDesc = nil
	file_api_proto_damage_damage_proto_goTypes = nil
	file_api_proto_damage_damage_proto_depIdxs = nil
}
